/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CowManager {
      
    export type ActionLogStruct = {behavior: BigNumberish, timestamp: BigNumberish}

    export type ActionLogStructOutput = [behavior: bigint, timestamp: bigint] & {behavior: bigint, timestamp: bigint }
  

    export type CowStruct = {id: BigNumberish, name: string, currentBehavior: BigNumberish, timestamp: BigNumberish, history: CowManager.ActionLogStruct[]}

    export type CowStructOutput = [id: bigint, name: string, currentBehavior: bigint, timestamp: bigint, history: CowManager.ActionLogStructOutput[]] & {id: bigint, name: string, currentBehavior: bigint, timestamp: bigint, history: CowManager.ActionLogStructOutput[] }
  
    }

  export interface CowManagerInterface extends Interface {
    getFunction(nameOrSignature: "addCow" | "cowCount" | "getAllCows" | "getCow" | "getCowHistory" | "isDoctor" | "owner" | "renounceOwnership" | "setDoctorStatus" | "transferOwnership" | "updateBehavior"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BehaviorUpdated" | "CowAdded" | "DoctorStatusChanged" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'addCow', values: [string]): string;
encodeFunctionData(functionFragment: 'cowCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllCows', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCowHistory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isDoctor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setDoctorStatus', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateBehavior', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addCow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cowCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllCows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCowHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDoctorStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateBehavior', data: BytesLike): Result;
  }

  
    export namespace BehaviorUpdatedEvent {
      export type InputTuple = [cowId: BigNumberish, newBehavior: BigNumberish, time: BigNumberish];
      export type OutputTuple = [cowId: bigint, newBehavior: bigint, time: bigint];
      export interface OutputObject {cowId: bigint, newBehavior: bigint, time: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CowAddedEvent {
      export type InputTuple = [id: BigNumberish, name: string];
      export type OutputTuple = [id: bigint, name: string];
      export interface OutputObject {id: bigint, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DoctorStatusChangedEvent {
      export type InputTuple = [doctor: AddressLike, status: boolean];
      export type OutputTuple = [doctor: string, status: boolean];
      export interface OutputObject {doctor: string, status: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CowManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): CowManager;
    waitForDeployment(): Promise<this>;

    interface: CowManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCow: TypedContractMethod<
      [_name: string, ],
      [void],
      'nonpayable'
    >
    

    
    cowCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAllCows: TypedContractMethod<
      [],
      [CowManager.CowStructOutput[]],
      'view'
    >
    

    
    getCow: TypedContractMethod<
      [_id: BigNumberish, ],
      [[bigint, string, bigint, bigint] & {id: bigint, name: string, currentBehavior: bigint, timestamp: bigint }],
      'view'
    >
    

    
    getCowHistory: TypedContractMethod<
      [_id: BigNumberish, ],
      [CowManager.ActionLogStructOutput[]],
      'view'
    >
    

    
    isDoctor: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setDoctorStatus: TypedContractMethod<
      [_doctor: AddressLike, _status: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateBehavior: TypedContractMethod<
      [_cowId: BigNumberish, _newBehavior: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCow'): TypedContractMethod<
      [_name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cowCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAllCows'): TypedContractMethod<
      [],
      [CowManager.CowStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCow'): TypedContractMethod<
      [_id: BigNumberish, ],
      [[bigint, string, bigint, bigint] & {id: bigint, name: string, currentBehavior: bigint, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getCowHistory'): TypedContractMethod<
      [_id: BigNumberish, ],
      [CowManager.ActionLogStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'isDoctor'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDoctorStatus'): TypedContractMethod<
      [_doctor: AddressLike, _status: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateBehavior'): TypedContractMethod<
      [_cowId: BigNumberish, _newBehavior: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BehaviorUpdated'): TypedContractEvent<BehaviorUpdatedEvent.InputTuple, BehaviorUpdatedEvent.OutputTuple, BehaviorUpdatedEvent.OutputObject>;
getEvent(key: 'CowAdded'): TypedContractEvent<CowAddedEvent.InputTuple, CowAddedEvent.OutputTuple, CowAddedEvent.OutputObject>;
getEvent(key: 'DoctorStatusChanged'): TypedContractEvent<DoctorStatusChangedEvent.InputTuple, DoctorStatusChangedEvent.OutputTuple, DoctorStatusChangedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'BehaviorUpdated(uint256,uint8,uint256)': TypedContractEvent<BehaviorUpdatedEvent.InputTuple, BehaviorUpdatedEvent.OutputTuple, BehaviorUpdatedEvent.OutputObject>;
      BehaviorUpdated: TypedContractEvent<BehaviorUpdatedEvent.InputTuple, BehaviorUpdatedEvent.OutputTuple, BehaviorUpdatedEvent.OutputObject>;
    

      'CowAdded(uint256,string)': TypedContractEvent<CowAddedEvent.InputTuple, CowAddedEvent.OutputTuple, CowAddedEvent.OutputObject>;
      CowAdded: TypedContractEvent<CowAddedEvent.InputTuple, CowAddedEvent.OutputTuple, CowAddedEvent.OutputObject>;
    

      'DoctorStatusChanged(address,bool)': TypedContractEvent<DoctorStatusChangedEvent.InputTuple, DoctorStatusChangedEvent.OutputTuple, DoctorStatusChangedEvent.OutputObject>;
      DoctorStatusChanged: TypedContractEvent<DoctorStatusChangedEvent.InputTuple, DoctorStatusChangedEvent.OutputTuple, DoctorStatusChangedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }